<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SystemView_All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>3503b84e-ff85-4c9b-aa56-2fdd2b181125</testSuiteGuid>
   <testCaseLink>
      <guid>44f4d1d6-024f-4cb9-842b-b4c4831f1ecd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3518911-dc2d-4f1a-88f8-a1d750d26a91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7497ea5e-4135-464c-8a9e-5c1e53dc7aee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b433ae84-59ac-4dbe-80d4-8ccadda0bed4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb91c1b4-c60f-4805-8bd0-8ca74cae62fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8283ccc8-bc74-45bc-abf0-9dc5f7d938fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73aa6a09-c2a9-4bee-86ad-470da1fa283f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_HideUnHide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2ef6ba-ccdd-43c8-a695-2a265860b60b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc8c0486-5d09-4098-9e40-0fa794d264ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_AssignToRole_Verify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aa05715-01c8-4117-b4d4-71b875213ca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54373d51-923b-4b74-a2e7-8a908fd58804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849ccf64-b040-4365-9219-8c7b3ef03416</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ffaed37-fbb8-4993-9ee7-a3225a28f909</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
