<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SystemView_All_20200624_202908</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>7d906161-e43d-4201-948f-e5a6cf8c2e3a</testSuiteGuid>
   
<testCaseLink>
      <guid>cb91c1b4-c60f-4805-8bd0-8ca74cae62fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8283ccc8-bc74-45bc-abf0-9dc5f7d938fc</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>73aa6a09-c2a9-4bee-86ad-470da1fa283f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_HideUnHide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2ef6ba-ccdd-43c8-a695-2a265860b60b</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>2e57224d-a4d3-4192-927e-31492cc5a1b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cadfdb2f-fa66-44f9-b57d-f86a30509833</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>dc8c0486-5d09-4098-9e40-0fa794d264ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint2/SystemView_Create_AssignToRole_Verify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aa05715-01c8-4117-b4d4-71b875213ca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54373d51-923b-4b74-a2e7-8a908fd58804</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849ccf64-b040-4365-9219-8c7b3ef03416</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ffaed37-fbb8-4993-9ee7-a3225a28f909</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
