<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ManageList_AllViews</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a0f81f9d-40c0-4f94-a08b-fa29b0512544</testSuiteGuid>
   <testCaseLink>
      <guid>a93c3732-f3f1-4443-b98a-f698a2a1748e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_HideUnhide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aae603f-e1e9-453a-a429-947bd0f81d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94419032-25c4-4192-94c3-c4b62031cfb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d735130e-11aa-413a-8c1e-f615290e3e1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8461b540-5b82-4bd9-b090-59ce2768af40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e80bf8d3-f650-4287-826e-53eeae9a5412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c63eee19-5625-4d57-aed0-8948bf4b08ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba2ad65-f176-4caa-88de-60fbc7045c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc31550-ba5e-4fbc-8ac8-4e80cee06543</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>881fa03d-f0a2-4ecd-bcde-1b1d7230f7c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba90927-83af-4aaa-a85d-eae54b3a0cb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a377abd4-e0d2-4bbc-8a27-9981603ca862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4ac66b2-3377-4110-8719-e8b8d5e50bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05f2880c-d67e-4ee6-863a-86b87bca4d47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3390cc2c-76a1-49ec-888c-5ec7415c4c9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cca392-691a-4c42-bfcb-4240d253f6fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ecab548-9b8f-40c4-87ca-12f240472076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65ec6fda-ec7d-491c-adae-ce0c3ec1f332</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8cd416c5-09ce-4a50-bc2f-d62219fbe939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28784031-11e4-43b7-a20b-cf7b532663d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446a9569-9950-4774-ba2f-344c78f1faa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddea0f74-f419-469d-8e25-4cfa2e48b563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a2ca428-4e5e-4959-95a2-485d5977db6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e5f8917-b1d0-4fbc-b729-1b48653f9b52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_HideUnhide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4cf81f-56fa-47a2-b62b-615afa202e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741eff12-2480-4024-a132-458ee62969d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e84c316-6a06-465a-a1f5-3f8e5a62ab4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a371ccd-6dfb-4c51-924c-0525fdc71c07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>013b2619-7dd6-4021-80f1-378d007fdf63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8880fd9-aaf4-4bc1-941b-3ee534515252</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e14d759-4996-463c-be94-7a9bdfeaf100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98204212-9746-40bf-8f4f-bf97048ed5c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59b9f41a-2464-40ff-a6c8-f62caf02735e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c26072a-deb4-487d-921b-8a91e8f76de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee53d18-072e-4c59-aae7-43a8799cbd22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b490094-17a8-42cc-a04a-49547af0e11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6dd3e08-a714-43e4-8cff-ef8ce70bd91e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b9c6d08-7ab5-4fff-85e1-0bf8723e9bb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da754904-291d-46a7-ad7a-9ecc276872a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d72bb3-86ce-4806-93b7-3e821a8eaaf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce0028c-a613-42c6-9b2a-c88457ccaea5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
