<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CreateUpdateDeleteUser</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>06ffc533-1006-4525-9115-5e2777771c31</testSuiteGuid>
   <testCaseLink>
      <guid>e9fed9d7-0a31-4e8d-94c8-7150ea57bd10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CreateUpdateDeleteUser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18e2fe7-e35b-4472-95b4-20ec615cc942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1655eec-8306-4f35-ae89-7605d5b25396</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3e5d99-5d00-4ed0-b731-6bc67ca7a695</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
