<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CustomView_All - Copy</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>5a91ad30-e9a9-4105-8206-aed167cd66bd</testSuiteGuid>
   <testCaseLink>
      <guid>fb0b130f-1276-486c-8e1c-bf98b4e0da83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_HideUnhide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aae603f-e1e9-453a-a429-947bd0f81d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94419032-25c4-4192-94c3-c4b62031cfb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d735130e-11aa-413a-8c1e-f615290e3e1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28b05364-7280-4d9e-8816-ad8c51f7d5c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e80bf8d3-f650-4287-826e-53eeae9a5412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c63eee19-5625-4d57-aed0-8948bf4b08ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba2ad65-f176-4caa-88de-60fbc7045c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc31550-ba5e-4fbc-8ac8-4e80cee06543</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfc84648-e9d0-47bf-8260-778e6009337a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba90927-83af-4aaa-a85d-eae54b3a0cb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a377abd4-e0d2-4bbc-8a27-9981603ca862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4ac66b2-3377-4110-8719-e8b8d5e50bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52a85300-fc88-4bc8-a8d2-ccad9668afe9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3390cc2c-76a1-49ec-888c-5ec7415c4c9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cca392-691a-4c42-bfcb-4240d253f6fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ecab548-9b8f-40c4-87ca-12f240472076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65ec6fda-ec7d-491c-adae-ce0c3ec1f332</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2a93330-09fd-4a9d-87cc-37e1c64195f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_CustomView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28784031-11e4-43b7-a20b-cf7b532663d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446a9569-9950-4774-ba2f-344c78f1faa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddea0f74-f419-469d-8e25-4cfa2e48b563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a2ca428-4e5e-4959-95a2-485d5977db6d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
