<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CustomView_All_20200806_184343</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>83a5c517-b027-4c65-8e37-7c83c0ced0ea</testSuiteGuid>
   <testCaseLink>
      <guid>e122c49c-42b3-4177-87de-167aaf6a4c2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39c6c3d4-bfda-4b9f-9a5c-5ce738b1236d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bcd9acd-f6cc-4c2c-8dbf-0c8bdf66c4e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb1bc45a-af34-4af9-9695-7ac65fbbe591</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c89f1ee-a88b-4a31-b905-e213ef731d0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e300b9-27df-42f7-9ec7-a384886d20df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f67f8729-5d30-4983-9d26-24b65aab9248</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>724694ef-fe35-4c14-b108-fd1e171cac80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3074977a-ac50-45ab-a015-7d1af7454cb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcb01c25-49cb-4906-a56b-8129fe156c5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c085d287-a190-4755-8053-3849329fb2c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_Create_ShareWithRole_Verify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1add4da-c16f-4213-b85c-37225955aba5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e39e29-c3c2-479f-a4ec-c971b02fbc4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe586aae-ffcc-47d9-b2ad-63c3e08f4652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e0768ab-5250-4c0c-8025-e8a9c3744935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdaf8452-291b-49e1-a4c9-a714d51a16d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/CustomView_Create_ShareWithUser_Verify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14f54b7f-c7d9-45e0-8af2-4cf913d5c498</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33534d4e-0cb9-4731-bbe2-3f467fea1f45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721babb9-818f-441c-9aa6-6362779cc983</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0286d296-0032-4aff-a351-a80a5810f699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab79abfe-d967-432f-974c-9f1d9e4047df</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
