<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_ManageList_SystemView_All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff304de6-2a80-431d-9e3b-35f7a7af22d9</testSuiteGuid>
   <testCaseLink>
      <guid>cd56b5f0-14c0-4d87-b106-3c14dd0431b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_HideUnhide_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4cf81f-56fa-47a2-b62b-615afa202e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741eff12-2480-4024-a132-458ee62969d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>778cca92-c1f0-42d1-b70b-d0d0d31dd4d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dae45c4-5ec2-4d74-856b-c264b5e32c0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_OntheFlyConfig_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a371ccd-6dfb-4c51-924c-0525fdc71c07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>013b2619-7dd6-4021-80f1-378d007fdf63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35fd597a-b3c5-4db4-9992-452d4e18dcf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8880fd9-aaf4-4bc1-941b-3ee534515252</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>568bdba4-c247-4b80-8893-75df745130e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_Create_SetDefault_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98204212-9746-40bf-8f4f-bf97048ed5c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59b9f41a-2464-40ff-a6c8-f62caf02735e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>831a7247-639a-4f50-99d2-00632a70d142</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a1d448c-b388-4668-ad18-a3a28e5aa8c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_CreateCopyDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee53d18-072e-4c59-aae7-43a8799cbd22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b490094-17a8-42cc-a04a-49547af0e11e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae142c02-7e9b-4b8b-8c86-edd57bb5582a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6dd3e08-a714-43e4-8cff-ef8ce70bd91e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57e5e669-b53a-4dc7-bc26-b307e0b0f03f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint6/ManageList_SystemView_CreateEditDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da754904-291d-46a7-ad7a-9ecc276872a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d72bb3-86ce-4806-93b7-3e821a8eaaf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bde1c9-40d2-420b-92cc-63d1b47371db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce0028c-a613-42c6-9b2a-c88457ccaea5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
