<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CreateSeasonFeature_Autonomous</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7172cf30-9494-46f9-8926-c6068bb30c95</testSuiteGuid>
   <testCaseLink>
      <guid>e0419b40-0fc6-4210-a84a-a343ff9f4598</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common/Launch the Browser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8ee6b56-9f2f-4825-81b3-dc7d3a4041f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87e83533-ef25-4f14-8d84-23381be250bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint1/Login/VerifyLoginSuccessfully</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>05b3b8ac-240f-4c45-901a-c658ebaf88da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint1/Create Season/Create_Update_Delete_And_VerifySeasonPositiveFlow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b71729f-8621-499b-b80f-edf76f42dc72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c6b5d5-619f-4178-bde7-37efb1a04120</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0dbad90-0653-481d-a800-c9dc4b73dfca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde19d7b-facf-4862-a8d5-41e817c142cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ce663fe-c2fe-47e1-8d8f-4ea8193fe2ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f1d906f-ebab-4c6f-a8bd-c23e1eb8f577</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c4be36-0951-410f-9110-17a0d9c78149</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e841717-ecb4-401e-bfaf-c25678afacc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d574a4a3-3097-4d69-b8e2-6c96a7a29df3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06b1446d-6315-4918-865f-e60b0676e3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a44c14d2-967f-4599-a17d-0d5764d76e3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7fcfe3c-9603-4f9c-b889-d2f7bb998a80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6d6637c-bbfd-4f4d-ba34-32efe8063746</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d06ce43b-2d46-4589-aa6e-1f3e78b82b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d5af7a3-0876-415f-ae37-6e90232bbd27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40987165-5deb-4aed-9a5c-a5bb5a57238e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>882c8b97-21bd-4129-a66d-ed2f7f318d21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c69249e3-6933-47fb-aafe-8638ff367306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28129dea-ba8d-470e-a6a7-72382be0b1c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
