<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CreateSeasonFeature_Excel_IE</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1d9f8082-b3b4-4831-b7cb-c2b4607baab2</testSuiteGuid>
   <testCaseLink>
      <guid>fb643820-8d10-42da-a9e4-8abd7a43be81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint1/Login/VerifyLoginSuccessfully</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ec46be81-fbe6-4ba9-a2f4-da18e7cd5086</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint1/Create Season/VerifyCreateSeasonValidations</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f82cff0-9cc4-4676-be8d-2d79e3e397d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1efe79-333f-4e69-9fca-07f1b1f2fcc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f14bfc-0c7b-472d-b90d-65028db8e281</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
