<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>e2c941f5-bd84-41e0-bbbc-9da66e0ee9f9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAATCAYAAAB/TkaLAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAFaADAAQAAAABAAAAEwAAAACHW+euAAABa0lEQVQ4Eb1UsU6EQBA9Fo2B0p4GKEhI6DUxEjs/gGh3f6Cdv6CJxXmFhZWJhbG9xtLQ+AdSiNhIrrhaCo4G3+wdyXhAJCe6ycDbeTOPGXZAGSyWUpblEv7upijKYIMkSJA2fSzSErj0o8YqEgz3Bv9H1Pf9LcdxtruW7XmejhyVx9cqTdN0XBTFh2mahzywCSPmIMuyKXJGnK+JgryEzTANE8uyhjyYY3BHiHmEfaqqes25mug7lqZpu5iKF9gtqjnjCYThOwF3D/gG0Z04jl95TE2UyCiKZkKIfSQ8YXuBqkYQkXm2bZ8DXMGedV3fS5JkKgl2oS9JzikEmHsBXdfdzPP8DjHU6gO8c+Ah8MQwjOMwDOerSfLhJEoGstGIQ6VjtFySAd8EQUCn3RpfCf74mULwFK9EoN1vJ91UaWfR1eS2PbXfeFBtCV39fyOKk+znR8raqOaI3i1zrw9pNCtRqbIcrbUVq66/AH6iiPOI6+BdAAAAAElFTkSuQmCC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_body_clone&quot;)/div[@class=&quot;rTableRow items class0 channel0&quot;]/div[@class=&quot;rTableCell freeze actions&quot;]/div[@class=&quot;actionMenu_dropdown_pop__1QSSQ&quot;]/div[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table_body_clone']/div[261]/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[261]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[261]/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
