<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_PT Business Administrator_checkbox_la_edbee9</name>
   <tag></tag>
   <elementGuidId>1841842b-8260-4f32-b95f-84ee865a0a1e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>QATEST</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_label userRole_roles_checkbox_label__piej3 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-tabs-1&quot;)/div[@class=&quot;userRole_rolesList__Mpwex&quot;]/div[@class=&quot;userRole_userRole_wrapper__2razL&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;table_body_scroll&quot;]/table[@class=&quot;userRole_permission_table__z2XS4&quot;]/tbody[1]/tr[6]/td[@class=&quot;text-center&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;checkbox_label userRole_roles_checkbox_label__piej3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-tabs-1']/div/div/div/div[2]/div/table/tbody/tr[6]/td/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/label</value>
   </webElementXpaths>
</WebElementEntity>
