<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NameDivisionSeasonYearTypeInternet</name>
   <tag></tag>
   <elementGuidId>732ca27d-cf46-44fa-b7e9-1512c85d85e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[(text() = 'NameDivisionSeasonYearTypeInternet Launch Start DateInternet Launch End DateIn Store Launch Start DateIn Store Launch End DateCreated ByCreated OnUpdated ByUpdated On' or . = 'NameDivisionSeasonYearTypeInternet Launch Start DateInternet Launch End DateIn Store Launch Start DateIn Store Launch End DateCreated ByCreated OnUpdated ByUpdated On')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createNewSeason']/div/div/div[2]/div[3]/div[3]/div/ul/li/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NameDivisionSeasonYearTypeInternet Launch Start DateInternet Launch End DateIn Store Launch Start DateIn Store Launch End DateCreated ByCreated OnUpdated ByUpdated On</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createNewSeason&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body pb-0&quot;]/div[@class=&quot;row ml-1 mr-1&quot;]/div[@class=&quot;col-lg-12 mt-3&quot;]/div[@class=&quot;dflex-column bottom-border&quot;]/ul[@class=&quot;viewForm_font_14__3Cjmu&quot;]/li[@class=&quot;dflex mt-2 mb-1&quot;]/div[@class=&quot;dflex&quot;]/div[@class=&quot;select-wrapper secondary-select&quot;]/select[@class=&quot;form-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createNewSeason']/div/div/div[2]/div[3]/div[3]/div/ul/li/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group By'])[3]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group By'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-Z'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
