<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_AllPages_PageLoadPerformance</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>bfd5eb26-81ea-4802-92be-d4f9b6695b59</testSuiteGuid>
   <testCaseLink>
      <guid>e3a3e8d4-a80d-428d-8251-3ec8ddc46b2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/Libraries</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>690e1c55-7693-43f2-81e6-df8b06050111</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-18</value>
         </iterationEntity>
         <testDataId>Data Files/Libraries</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>690e1c55-7693-43f2-81e6-df8b06050111</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SubMenu</value>
         <variableId>8e455d14-50bf-402c-8b16-a058113ba8a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d259351-319e-46dc-bd31-6f6366546006</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>690e1c55-7693-43f2-81e6-df8b06050111</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Brand</value>
         <variableId>78a941e1-11d3-4931-8ada-4c0a388502b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>690e1c55-7693-43f2-81e6-df8b06050111</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Division</value>
         <variableId>f1bd8e8c-ba62-4609-8d6f-d1a0dfee15ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>690e1c55-7693-43f2-81e6-df8b06050111</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Season</value>
         <variableId>29aedef0-e9eb-415a-ba8c-6066980d37c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dff8dd8d-f708-4845-903a-2e94f5f9abee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/Manage Types</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65e6096a-23d1-4cd8-8ea1-706b70f4161a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-18</value>
         </iterationEntity>
         <testDataId>Data Files/Libraries</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>65e6096a-23d1-4cd8-8ea1-706b70f4161a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SubMenu</value>
         <variableId>748be911-f7b4-4a7f-8ee0-b24dc15cd9ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8731daaf-f2fe-49c0-af68-21a046d42b23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aafb7a65-1850-4507-ab1c-52e56582bd9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/UserRoleManagement</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Roles&quot;</value>
         <variableId>0982aab6-6d3c-4c5b-8a4c-457cec4da3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82e62723-b5c7-4c19-9cc3-7e11e4bff23e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be25c186-b866-4ea5-a1d1-0f7ee19d979a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/UserRoleManagement</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Permissions&quot;</value>
         <variableId>0982aab6-6d3c-4c5b-8a4c-457cec4da3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82e62723-b5c7-4c19-9cc3-7e11e4bff23e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9176779a-3851-4b2b-80cd-d2da33cbf1d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/UserRoleManagement</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Users&quot;</value>
         <variableId>0982aab6-6d3c-4c5b-8a4c-457cec4da3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82e62723-b5c7-4c19-9cc3-7e11e4bff23e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
