<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_MerchList_PageLoadPerformance_Lighting</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>19ad32e7-f56c-4ecf-bd9e-6a3eedfe5a55</testSuiteGuid>
   <testCaseLink>
      <guid>25248cfd-0fa0-4d31-90b3-a0ae57c00ceb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/MerchList/MerchList_Library</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>812822c0-6c29-47cb-bf68-393db1bc72d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de49bf9c-f80d-4830-a344-7fbb938c1a74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1288d3e-e271-473e-9847-3a8ab261ba63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Lighting>805 - WE LIGHTING&quot;</value>
         <variableId>177efeab-aec7-4a46-aa15-d1810cf432db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;WE Lighting Fall 2020&quot;</value>
         <variableId>4c5fa0e9-7abc-4f4c-9591-ca4a46168724</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
