<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_MerchListPagination_SingleSession_TimeOutExpiryTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d83d22f6-2794-4a5c-99c3-3d59d1ca4122</testSuiteGuid>
   <testCaseLink>
      <guid>5692bec0-66c4-488a-ae31-e27751168d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PageLoadPerformance/MerchListPagination_SingleSession_TimeOutExpiryTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce6f19c5-f2d2-467a-8d0a-efb254d29315</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf4d9f4a-b983-4283-bcf2-f5332e900b32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5243db39-0f14-4452-a5e7-dea7b59a0445</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efe1c594-7b81-4a4b-a171-859af1ea4ea1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b3dceb-ca0d-4bf2-932a-afce3d4f62d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
