<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CustomView_HideUnHideColumn</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>682a0100-e712-47c6-82d1-569557d56bbf</testSuiteGuid>
   <testCaseLink>
      <guid>b4d95d98-8340-4be8-b9a0-bdaf311619d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint8/CustomView_Create_HideUnHideColumn_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a5c8cb3-5298-4e3e-b63f-0ed11a529d7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b8c313f-c5a2-4fb9-b46c-13c1b79fd5d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ff75a2-63f3-4f8b-b875-9d93c526f9bd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
