<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SystemView_HideUnHideColumn</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c51c9ae7-3236-447a-aecb-75afb6f22bef</testSuiteGuid>
   <testCaseLink>
      <guid>c5e21890-310e-4ce7-a539-e483dc7b8176</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint8/SystemView_Create_HideUnHideColumn_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>016960c8-5ca7-440b-8b92-9afdabe2d8dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fd58249-40d3-4725-91ed-2f3c2eba0360</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a523eec-c238-4b52-bc12-754fb334b3e9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
