<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CreateUpdateDeleteCollection</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>4f9bb4e3-1dbc-4340-b004-055f6e6acdfc</testSuiteGuid>
   <testCaseLink>
      <guid>83c1b688-109b-4a30-9e81-e9ff29a2cf53</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint5/CreateUpdateDeleteCollection</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc533ae-4867-48d5-9358-2cefda8c9316</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed89baf-8ad9-40d3-bb29-3b80d27f2a51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>398eadda-cf2d-4108-be2a-e440bf7e9521</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
