<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CreateUpdateDeleteCountry</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>f5ba7cf4-1db4-4208-aeac-5156cba804db</testSuiteGuid>
   <testCaseLink>
      <guid>63d03a8b-d91c-4139-bad0-e54195fa3fc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint5/CreateUpdateDeleteCountry</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffb3ca1-c7ca-4f59-a113-033f5ab6c948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51daf909-1171-40d3-93b1-cd81a7d12eb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6e485d-f655-4cc3-9a25-bf734ca61f23</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
