<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CreateUpdateDeleteLadingPort</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>ff08bf13-33a9-46b1-9bc2-967a8ca1a883</testSuiteGuid>
   <testCaseLink>
      <guid>ce020871-18b9-433e-904b-021de6bf7a54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint5/CreateUpdateDeleteLadingPort</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed07ebcb-65df-4ed4-a85e-92ee9df1a44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6e45cc9-df16-4a46-9d0d-5a6d6de5566a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74e9bf31-cc13-46be-b8e6-100dbe20563d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
