<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_InStoreLaunchEnd_checkbox_label</name>
   <tag></tag>
   <elementGuidId>6a12ffac-9cb5-45fc-a8e7-f517f4064896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for = 'TYPE6']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='In Store Launch End Date']/..//label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_label </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>TYPE6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;manageLibrary_manage_library_container__wTwBZ&quot;]/div[@class=&quot;manageLibrary_content_section__3Wmoy&quot;]/div[@class=&quot;layoutForm_attribute_group_container__2YfxQ&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9&quot;]/div[1]/div[@class=&quot;general_atribute&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;layoutForm_group_column_container__35DwT&quot;]/ul[1]/li[3]/div[@class=&quot;checkbox columnLayout_check_box__2N9O2&quot;]/label[@class=&quot;checkbox_label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/div/div/table/tbody/tr/td/ul/li[3]/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/label</value>
   </webElementXpaths>
</WebElementEntity>
